# Generated by Django 4.0.2 on 2022-02-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chat_connection_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.DeleteModel(
            name='Chat_Connection',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
